import { AppKitScaffold } from '@reown/appkit-react-native'
import { optimism } from '@reown/appkit/networks'

const images = {
    authBgImage: require('../images/authBgImage.png'),
    splashLogoImage: require('../images/splashLogoImage.png'),
    splashScreenBg: require('../images/splashScreenBg.png'),
    DepositLogo: require('../images/DepositLogo.png'),
    UsdtLogo: require('../images/UsdtLogo.png'),
    BtcLogo: require('../images/BtcLogo.png'),
    SolLogo: require('../images/SolLogo.png'),
    EthLogo: require('../images/Eth.png'),
    AvaxLogo: require('../images/AvaxLogo.png'),
    backArrow: require('../images/backArrow.png'),
    rightArrow: require('../images/rightArrow.png'),
    userProfileImg: require('../images/userProfileImg.png'),
    profileSettingIcon: require('../images/profileSettingIcon.png'),
    securitySettingIcon: require('../images/securitySettingIcon.png'),
    systemSettingIcon: require('../images/systemSettingIcon.png'),
    addressSettingIcon: require('../images/addressSettingIcon.png'),
    emailNotificationSettingIcon: require('../images/emailNotificationSettingIcon.png'),
    placeholderProfileImg: require('../images/placeholderProfileImg.png'),
    AccountVerify: require("../images/AccountVerify.png"),
    depositFilter: require('../images/filterarrow.png'),
    union: require('../images/Union.png'),
    activeFilter: require('../images/arrowAbove.png'),
    searchSign: require('../images/searchSign.png'),
    tickIcon: require('../images/tickIcon.png'),
    clockIcon: require('../images/clockIcon.png'),
    infoIcon: require('../images/infoIcon.png'),
    checkBox: require('../images/checkBox.png'),
    toggleSwitchOn: require('../images/toggleSwitchOn.png'),
    toggleSwitchOff: require('../images/toggleSwitchOff.png'),
    testQrImg: require('../images/testQrImg.png'),
    tickBoxes: require('../images/tickBoxes.png'),
    home: require("../images/home.png"),
    market: require("../images/Market.png"),
    Exchange: require("../images/Exchange.png"),
    Wallet: require("../images/Wallet.png"),
    Setting: require("../images/Setting.png"),
    dashboardGraph: require("../images/DummyImage/DashboardDummyGraph.png"),
    doughnutChart: require("../images/Doughnut.png"),
    tron: require("../images/tron.png"),
    optimism: require("../images/optimism.png"),
    polygon: require("../images/polygon.png"),
    arbitrum: require("../images/arbitrum.png"),
    aptos: require("../images/aptos.png"),
    infoCircle: require("../images/infoCircle.png"),
    downloadIcon: require("../images/downloadIcon.png"),
    qrcode: require("../images/qrcode.png"),
    rightArrow: require('../images/rightArrow.png'),
    backArrow: require('../images/backArrow.png'),
    rightsign: require('../images/rightsign.png'),
    doughtnut:require('../images/Doughnut.png'),
    checkMark: require("../images/checkMark.png"),
    arrowUp: require("../images/arrowUp.png"),
    arrowDown: require("../images/arrowDown.png"),
    Deposit: require("../images/Deposit.png"),
    copyIcon: require("../images/copyIcon.png"),
    ethIcon: require("../images/ethIcon.png"),
    Document :require("../images/Document.png"),
    News1:require("./DummyImage/News1.png"),
    News2:require("./DummyImage/News2.png"),
    CryptoWallet:require("./CryptoWallet.png"),
    DrawerExchange:require("./drawerExchange.png"),
    DrawerMarket:require("./DrawerMarket.png"),
    Address:require("./Address.png"),
    Contact:require("./Contact.png"),
    Logout:require("./Logout.png"),
    copesIcon: require("../images/copesIcon.png"),
    filterMaarketHeader:require("./filterMarket.png"),
    starFill:require("./starFill.png"),
    starUnFill:require("./starUnFill.png")
}
export default images