
export const Routes = {
    AuthNavigator: "AuthNavigator",
    AppNavigator: "AppNavigator",
    BottomNavigator: "BottomNavigator",
    splashScreen: "splashScreen",
    LoginScreen: "LoginScreen",
    SignupScreen: "SignupScreen",
    EmailVerificationScreen: "EmailVerificationScreen",
    IntroductMainScreem: "IntroductMainScreem",
    Home: "Home",
    MarketScreen: "MarketScreen",
    ExchangeScreen: "ExchangeScreen",
    WalletScreen: "WalletScreen",
    WalletHome: "WalletHome",
    settingMain: "settingMain",
    settingProfile: "settingProfile",
    DepositHistory: "DepositHistory",
    settingSecurity: "settingSecurity",
    twoFactorAuth: "twoFactorAuth",
}