import { DepositHistory, SelectNetwork } from "../../screens/App/Index";

export const Routes = {
    AuthNavigator: "AuthNavigator",
    AppNavigator: "AppNavigator",
    BottomNavigator: "BottomNavigator",
    splashScreen: "splashScreen",
    LoginScreen: "LoginScreen",
    SignupScreen: "SignupScreen",
    EmailVerificationScreen: "EmailVerificationScreen",
    IntroductMainScreem: "IntroductMainScreem",
    Home: "Home",
    MarketScreen: "MarketScreen",
    ExchangeScreen: "ExchangeScreen",
    WalletScreen: "WalletScreen",
    WalletHome: "WalletHome",
    settings: "settings",
    settingProfile: "settingProfile",
    DepositHistory: "DepositHistory",
    settingSecurity: "settingSecurity",
    twoFactorAuth: "twoFactorAuth",
    changePassword: "changePassword",
    antiPhishingCode: "antiPhishingCode",
    SelectNetwork: "SelectNetwork",
    Barcode: "Barcode",
    Deposit: "Deposit",
    settingSystem: "settingSystem",
    addressBook: "addressBook",
    addressDetailsExpanded: "addressDetailsExpanded",
    SelectCrypto: "SelectCrypto",
}